"""One module per strategy, each defining view_<NAME>(df, tf). Loaded by paperbot.strategy_views
after the locked code is verified (the modules import the vendored indicator code)."""

NAMES = (
    "S2_ST_ROC",
    "S5_DONCHIAN_MFI",
    "S6_EMA_DMI_ADX",
    "N01_ST_EMA",
    "N02_ST_KST",
    "N03_ADX_GC",
    "N07_ICHI_CMO",
    "N08_ICHI_WR",
    "N09_ALLIG_AROON",
    "N10_HA_PSAR",
    "N12_ICHI_AO",
    "N14_ICHI_RSI",
    "N17_KC_RSI",
    "N18_VWMA_MACD",
    "N21_ST_RSI_ADX",
    "N22_VORTEX_PSAR",
    "N23_HA_ST",
    "N24_DMI",
    "N25_DST_CCI",
    "OBV_S",
    "OBV_B",
    "V39_ALL",
    "V45_AMB",
    "DOGE",
    "S1_EMA_RSI_CHOP",
    "S3_CMO_SANDWICH",
    "S4_BB_BBP",
    "N04_ST_KLINGER",
    "N05_PSAR_POC",
    "N06_MACD_ORB",
    "N11_BREAKAWAY",
    "N13_3OUTSIDE",
    "N15_KC_AO",
    "N16_BBRSI",
    "N19_FIB_CHOP",
    "N20_EMA9_CHOP",
)
