// 📚 도입 기술: 대표님이 준 오픈소스 23개를 분석해 어느 부서에 무엇을 넣었는지 (코드 복사 없이 규칙·공식만 다시 만듦)
// status(10/5 코드 감사 기준): 실동작 = 매매·크기·관문 결정을 실제로 바꿈 · 표시용 = 표·설명만 · 부분 = 일부만 · 참고 = 아이디어만
export const TECH = [
  {repo: "freqtrade/freqtrade", lic: "GPL-3.0", teams: ["opt", "tpsl", "bt", "demo"], status: "실동작 — 백테스트+데모 모두 ROI표·수익후 추적손절·보호장치 잠금",
    what: "시간별 목표 수익표(minimal_roi) · 수익 오프셋 뒤 추적손절 · 보호장치 4종(StoplossGuard·MaxDrawdown·CooldownPeriod·LowProfitPairs) · 하이퍼옵트 손실함수 10종(Sharpe·Sortino·Calmar·ProfitDrawDown·MultiMetric·ShortTradeDur 등)과 ROI/손절/추적손절 탐색 공간 · 기대값 비율",
    where: "백테스터(nuri-ai/quant.js risk.minimal_roi·protections) · 전략 최적화팀 '하이퍼옵트' 업무 · 백테스트팀 '검증 보강' 표"},
  {repo: "mementum/backtrader", lic: "GPL-3.0", teams: ["bt", "opt", "demo"], status: "실동작 — SQN이 신뢰점수·자동 은퇴에 반영(VWR 등은 표시)",
    what: "성과 분석기: SQN(등급) · VWR(변동성 가중 수익, 코드 기본값 tau 0.2·sdev_max 2.0) · Returns 연환산 · DrawDown 최장 물림 · TradeAnalyzer 연승·연패",
    where: "백테스트팀 '검증 보강' 표 · 전략 최적화팀 결과표 (lib/hyperopt.js analyzers)"},
  {repo: "nautechsystems/nautilus_trader", lic: "LGPL-3.0", teams: ["qrisk", "live", "entry"], status: "실동작 — 데모 진입 고정리스크 사이징(손절 시 손실 상한)",
    what: "주문 전 리스크 엔진 점검 순서(축소 전용·가격/수량 단위·최소/최대·주문당 금액·거래 상태·제출 속도) · 거래 상태 ACTIVE/REDUCING/HALTED · TWAP 분할 · 고정 위험 사이저",
    where: "퀀트 리스크팀 '주문 전 점검표' · 실거래 데스크(거래 상태·TWAP 계획) · 진입 타점팀 '1% 위험 크기' (lib/execution.js) — 실제 주문은 여전히 보호 파일 live.js 한도·승인"},
  {repo: "vnpy/vnpy", lic: "MIT", teams: ["qrisk", "live", "ml"], status: "실동작 — 알파 순위(Alpha158식) 하위 1/3 롱·상위 1/3 숏 진입 크기 0.75배",
    what: "리스크 매니저(주문 흐름·하루 거래 한도) · 아이스버그 분할 · Alpha158 계열 팩터(KMID·KLEN·ROC·MA·STD·BETA·RSV·CORR) + 견고 z점수 횡단면 순위",
    where: "주문 전 점검표 · 머신러닝·딥러닝팀 '알파 팩터 순위' (lib/alpha.js) · N분봉 합성은 기존 차트 터미널(3·6·8·10분봉)에 이미 있음"},
  {repo: "ccxt/ccxt", lic: "MIT", teams: ["data", "situ"], status: "실동작 — 거래소 비교의 김치 프리미엄 5%↑ 롱 0.7배 + 바이낸스 펀딩 이력 과열 시 0.5배",
    what: "통일 API 개념으로 8개 거래소 공개 시세·펀딩·미결제약정 맞추기(바이낸스·바이비트 v5·OKX v5·비트겟 v2·코인베이스·크라켄·업비트·빗썸) · 단위 함정(OKX 계약·소수 변동률·펀딩 주기) · 김치 프리미엄 · 거래소별 요청 간격",
    where: "데이터 플랫폼팀 '거래소 비교' (lib/exchanges.js) — 라이브러리 자체(수 MB)는 넣지 않고 공개 주소만 사용"},
  {repo: "openbq-org/OpenBB (OpenBB ODP 미러)", lic: "Apache-2.0", teams: ["news", "data"], status: "실동작 — 미국 고영향 일정(CPI·FOMC·고용 등) ±30분 데모·뉴럴 진입 차단",
    what: "공급원(provider) 구조 · 키 없이 쓰는 공개 주소: Nasdaq 경제 캘린더 · 뉴욕 연준 SOFR · FRED CSV · Deribit DVOL",
    where: "뉴스·경제지표팀 '경제 캘린더·금리·변동성 지수' 업무 — 일부 사이트는 브라우저 차단(CORS)이 있어 GHCoin.exe 실행기로 받음"},
  {repo: "goldmansachs/gs-quant", lic: "Apache-2.0", teams: ["qrisk"], status: "실동작 — VaR·낙폭 판정 → 데모·실거래 진입 관문",
    what: "시계열: 수익률 · 연율 변동성(표본 표준편차 × √연간 관측, 코인은 365) · EWMA 변동성 · 상관 · 베타 · z점수 · 백분위 · 최대 낙폭 · 튀는 값 다듬기 · 시나리오 충격(비트코인 −30%, 알트는 베타만큼) + 역사적·모수 VaR/CVaR",
    where: "퀀트 리스크팀 '코인별 위험'·'스트레스 시험' (lib/riskq.js)"},
  {repo: "goldmansachs/jdmn", lic: "Apache-2.0", teams: ["qrisk", "demo", "live"], status: "실동작 — 리스크 결정표(거래정지·진입보류·비중절반) → 진입 관문",
    what: "DMN 결정표: 단항 검사(-, <, [a..b], (a..b], not(), 목록) · 적중 정책 UNIQUE·FIRST·PRIORITY·ANY·COLLECT(+,<,>,#)·RULE/OUTPUT ORDER · 기본 출력 · 맞은 규칙 번호 기록",
    where: "퀀트 리스크팀 '리스크 판정' 결정표 · 데모→실거래 '승격 결정표'(거부>검토>데모 더>승인) (lib/dmn.js)"},
  {repo: "goldmansachs/legend-engine · legend-studio · legend-sdlc · finos/legend", lic: "Apache-2.0", teams: ["data", "dev", "hq"], status: "실동작 — 전략 제약 검사(위반이면 백테스트 전 반려)",
    what: "데이터 모델 제약(Error는 막고 Warn은 경고, 결함 모두 모음) · 작업공간→검토→승인→버전 흐름 · 버전 번호(논리 변경 MAJOR · 파라미터 MINOR · 위험 설정 PATCH) · 경로별 차이(diff)",
    where: "매매법 개발 전 '전략 제약 검사' · 백테스트 통과 시 버전 발행 · 하이퍼옵트 결과 검토·승인 · 캔들 품질 검사 (lib/sdlc.js)"},
  {repo: "goldmansachs/obevo", lic: "Apache-2.0", teams: ["data", "hq"], status: "실동작(인프라) — 저장소 이전",
    what: "변경 이름 + 체크섬 적용 기록 · 이미 한 변경은 건너뜀 · 내용이 바뀐 변경은 멈추고 알림 · 실패 시 백업으로 되돌림 · 다시 돌려도 되는 변경",
    where: "앱 시작 때 저장소 이전(lib/migrate.js) · 데이터 플랫폼팀 상태표"},
  {repo: "goldmansachs/reladomo", lic: "Apache-2.0", teams: ["data", "ic", "qrisk"], status: "실동작 — 감사 해시 사슬 끊김 시 승격 보류 + 데모 시작 해시≠현재 전략이면 승격 불가",
    what: "이중 시간(업무 시간 from~thru · 처리 시간 in~out) · 감사 전용 기록 · 정정은 새 행(옛 기록 보존) · as-of 조회 · 해시 사슬 검증",
    where: "투자위원회 결정·채점, 리스크 판정, 백테스트, 하이퍼옵트 버전 기록 (lib/journal.js)"},
  {repo: "TauricResearch/TradingAgents", lic: "Apache-2.0", teams: ["ic"], status: "실동작 — 투자위원회 결정 20시간 동안 반대 방향 진입 차단",
    what: "애널리스트 4명(시장·여론·뉴스·펀더멘털) → 강세·약세 토론(1라운드) → 리서치 매니저 5단계 등급 → 트레이더(절대 가격만) → 공격·보수·중립 리스크 토론 → 위원장 최종 등급 · '의견 충돌은 관망 사유가 아님' · 해석 불가는 REVIEW(거래 금지) · 5봉 뒤 비트코인 대비 알파 채점 → 2~4문장 교훈 → 최종 결정자에게만(같은 코인 5 + 다른 코인 3, 시점 이전 것만)",
    where: "새 부서 '투자위원회' (coin-office icJob) · 뉴스팀 여론 밴드"},
  {repo: "HKUDS/Vibe-Trading", lic: "MIT", teams: ["dev", "bt", "opt", "news"], status: "실동작 — 견고성 관문(운일확률·구간일관성·위생): 매매법·봇·뉴럴 설계 전부",
    what: "말 → 전략 → 백테스트 흐름의 위생 관문(거래 0건·NaN 금지, 늦은 첫 거래·낮은 노출·끝까지 열린 포지션 경고) · 순열 검정 p · 부트스트랩 샤프 구간 · 5구간 검증 · 펀딩 상태(과열·쏠림) 규칙",
    where: "백테스트팀 '검증 보강' · 전략 최적화팀 채택 조건 · 승격 결정표 (lib/robust.js, exchanges.fundingRegime)"},
  {repo: "BennyThadikaran/stock-pattern", lic: "GPL-3.0", teams: ["pattern"], status: "실동작 — 순 패턴 방향 반대면 진입 크기 0.7배",
    what: "피벗(좌우 6봉, 마감 봉만 → 미래 참조 없음) · 허용오차 = 봉 길이 중앙값 · 쌍봉·쌍바닥 · 헤드앤숄더(역) · VCP · 깃발 · 추세선(3번 닿음)",
    where: "차트·캔들 패턴팀 '패턴 스캐너' (lib/patterns.js) + 형성→돌파→목표/실패 상태"},
  {repo: "zeta-zetra/chart_patterns", lic: "라이선스 없음(아이디어만)", teams: ["pattern"], status: "실동작 — 패턴 스캔 판정(위 관문)에 포함",
    what: "피벗 회귀선 분류(삼각수렴·깃발·페넌트·쌍봉) — 기울기를 ATR/봉으로 정규화하고 쐐기·채널을 더함, 원본 버그(한쪽 점만 확인) 수정",
    where: "패턴 스캐너의 기하 패턴 부분 (코드 없이 규칙만)"},
  {repo: "BitOracle-bitoracle/bitoracle-ai-server", lic: "라이선스 없음(아이디어만)", teams: ["ml"], status: "실동작 — 확률 0.6 규칙: 자체 AI 반대 확신 60%↑ 진입 차단",
    what: "다음 1시간 상승 확률 밴드: p ≥ 0.60 진입 · 0.40~0.60 무거래 · 손절 −3% · 익절 +5% (모델은 실시간 데이터로 스케일러를 다시 맞추는 문제가 있어 가져오지 않음)",
    where: "머신러닝·딥러닝팀 ML 확률 전략 규칙"},
  {repo: "iliaal/tradingview-mcp", lic: "MIT", teams: ["combo"], status: "실동작 — 종합 평점 −0.5 이하 반대 방향 진입 0.6배(데모·뉴럴)",
    what: "트레이딩뷰 데스크톱 조작용(주문 없음) — 우리 앱엔 데스크톱 연결이 없어 '기술적 분석 요약'(이평 15표 + 오실레이터 11표, 강한 매수~강한 매도)을 MIT python-tradingview-ta 규칙으로 직접 계산",
    where: "실시간 종합 지표 타점판 'TV 요약' 열 · 투자위원회 시장 보고 (lib/ta_rating.js) + 캔들 패턴 17종"},
  {repo: "johnmackintosh/runcharter", lic: "GPL-3.0", teams: ["demo"], status: "실동작 — 성과 하락 이동 감지 시 진입 크기 절반(회복 시 원복)",
    what: "런 차트: 처음 13점 중앙값 → 9연속 위/아래면 지속 이동 → 그 9점으로 새 중앙값 (중앙값과 같은 점은 건너뜀)",
    where: "데모거래팀 '성과 이동 감지' · 승격 결정표의 '악화' 입력 (lib/runchart.js)"},
  {repo: "jh941213/my-cc-harness", lic: "MIT", teams: ["hq"], status: "실동작 — QA 65점 미만·치명적 문제면 수정안 자동 반려",
    what: "독립 QA(만든 사람과 다른 직원) 100점 채점: 기능 40 · 품질 25 · 군더더기 없음 20 · 사용성·보안 15, 85↑ 통과 · 65~84 조건부 · 치명적 하나면 불합격 · 증거 없는 완료 금지",
    where: "CEO실 코드 수정안 → QA 채점 후 대표 승인"},
  {repo: "enarjord/passivbot", lic: "Unlicense(공개)", teams: ["bot"], status: "실동작 — 같은 코인·같은 방향 2개 넘으면 진입 차단(지갑 노출 한도) + 그리드 시뮬",
    what: "그리드·DCA(물타기) 봇 방식: 간격·물타기 배수(ddown)·최대 물타기·지갑 노출 한도·익절 마크업. 핵심은 '무한 물타기 금지'를 위한 지갑 노출 한도·물타기 횟수 상한",
    where: "자동매매봇팀 '그리드/DCA 연구 백테스트' (lib/botsim.js) — 청산 위험 때문에 연구용 백테스트로만, 실거래로는 안 나감"},
  {repo: "jesse-ai/jesse", lic: "MIT", teams: ["bot"], status: "부분 적용",
    what: "전략 클래스 방식(진입·청산·손절·익절·포지션 사이징)과 백테스트 구조 → 추세추종·평균회귀 봇 전략",
    where: "자동매매봇팀 '추세추종 봇'·'평균회귀 봇' 전략 (coin-office BOT_TEMPLATES)"},
  {repo: "Drakkar-Software/OctoBot", lic: "GPL-3.0(코어)·LGPL(텐타클)", teams: ["bot"], status: "부분 적용",
    what: "트레이딩 모드(그리드·DCA·돌파·신호)와 평가기 개념 → 돌파·슈퍼트렌드 봇 전략",
    where: "자동매매봇팀 '돌파 봇'·'슈퍼트렌드 플립 봇'"},
  {repo: "conor19w/Binance-Futures-Trading-Bot", lic: "라이선스 없음(규칙만)", teams: ["bot"], status: "실동작 — 삼중 EMA+스토RSI 봇 템플릿 → 검증 통과 시 데모",
    what: "바이낸스 선물 TA 봇의 진입·손절·익절·레버리지 방식 → 추세추종·돌파 봇의 조건·한도",
    where: "자동매매봇팀 봇 전략"},
  {repo: "Erfaniaa/crypto-trading-strategy-backtester", lic: "GPL-3.0(규칙만)", teams: ["bot"], status: "실동작 — 다른 코인 3개+ 중 1개 이하 수익이면 데모 투입 차단(과최적화)",
    what: "단순 교차 전략 백테스트 방식 → 평균회귀·추세 봇 참고",
    where: "자동매매봇팀 봇 전략"},
  {repo: "freqtrade/freqtrade", lic: "GPL-3.0", teams: ["bot"], status: "실동작 — 백테스트+데모 모두 ROI표·수익후 추적손절·보호장치 잠금",
    what: "(이미 최적화팀에 반영) ROI 표·추적손절·보호장치를 봇 전략에도 사용",
    where: "자동매매봇팀 '추세 캐리 봇'(minimal_roi) 등"},
  {repo: "RanitManik/gemini-clone", lic: "MIT", teams: ["hq"], status: "적용",
    what: "빈 방 추천 질문 카드 · 최근 질문 목록(방별, 중복 제거 20개) · 한글 입력 중 Enter 오작동 막기",
    where: "본부 채팅창"},
  {repo: "TLSRUF/ai-trader-team", lic: "MIT", teams: ["selfai", "coinai", "tpsl", "bt"], status: "실동작 — 켈리 우위 없음 0.5배·손익비<1.2 0.6배·포트폴리오 히트 6% 초과 차단",
    what: "원본 소스를 vendor/ai-trader-team/ 에 그대로 보관하고, 브라우저용으로 충실히 이식(출력 일치 테스트): trading_rigor.py→lib/rigor.js(포지션 사이징·손익비·R-멀티플·켈리·히트·상관), backtest.py→lib/attbacktest.js(SMA 돌파·손절·R:R 백테스트 + 계좌 복리·히트 한도). 다중 에이전트 합의는 자체 AI 확신도에도 반영",
    where: "vendor/ai-trader-team/*.py(원본) · lib/rigor.js·lib/attbacktest.js(이식) · 코인 AI 봇(계산·백테스트 명령) · 자체 AI 데스크 예시 계획"},
  {repo: "jnMetaCode/agency-agents-ko", lic: "MIT", teams: ["selfai", "coinai"], status: "실동작 — 팀별 핵심 원칙·성공 지표를 모든 직원 프롬프트에 주입",
    what: "finance/투자 리서처 에이전트의 핵심 원칙(강세·약세 동등 검증·반증 조건·확신 수준·하방 수치화)을 코인 AI 봇 지식으로 이식 + 자체 AI 데스크 11인 역할 분담",
    where: "코인 AI 봇 지식(coinai.js APP_KB 투자 리서치 원칙) · 자체 AI 데스크 팀 구성(coin-org.js)"},
  {repo: "anthropics/claude-cookbooks", lic: "MIT", teams: ["selfai", "ml"], status: "실동작 — 자체 AI 앙상블 판정이 진입 관문에 사용",
    what: "앙상블·LLM-판정(평가자) 패턴, 도구 합성 레시피 → 여러 신호를 가중 합성하고 '우위(edge)'로 신뢰를 조정하는 구조",
    where: "자체 AI 앙상블 가중·ML 우위 반영 (lib/selfai.js)"},
  {repo: "anthropics/financial-services", lic: "MIT", teams: ["selfai", "qrisk"], status: "실동작 — 뉴럴 데스크 상시 실행: 검증된 전략 신호 → AI 승인 → 청산공식 사이징",
    what: "금융 에이전트의 리스크·확신도 프레이밍(단정 금지, 참고값·면책) → 자체 AI 확신도 상한 95·'판단만 함' 표기",
    where: "자체 AI 데스크 표·해설, 리스크 문구"},
  {repo: "anthropics/claude-code", lic: "범용(패턴만)", teams: ["hq"], status: "참고",
    what: "에이전트-도구 호출·코드 수정 검토 패턴 → 자가 코드 수정(selfdev) 안전 검토 흐름의 참고(기존 기능)",
    where: "본부 코드 수정(selfdev) — 이번에 새 코드로 반영한 것은 없음, 패턴 참고"},
  {repo: "continuedev/continue · langgenius/dify · FlowiseAI/Flowise · Mintplex-Labs/anything-llm", lic: "각 OSS", teams: ["selfai", "coinai", "hq"], status: "적용",
    what: "이들이 공통으로 쓰는 'OpenAI 호환 커스텀 모델 제공사(base URL·모델·키 직접 입력)' 방식 → GH Coin 에 내 API 직접 연결 추가. 외부 API 가 사무실·자체 AI 의견·코인 AI 봇에 실제로 쓰인다",
    where: "engine.js custom 제공사·setCustomApi, launcher main.go X-Nuri-Base 서버 중계, [🔑 AI 연결]의 '내 API 직접 연결'"},
  {repo: "ten-builder/ten-builder (TEN)", lic: "Apache-2.0", teams: ["selfai"], status: "실동작 — 신호를 부품처럼 합성: 자체 AI 앙상블 → 진입 관문",
    what: "실시간 에이전트를 조합형 확장(extension) 그래프로 구성하는 개념 → 신호를 부품처럼 더하고 빼는 앙상블 구성(음성·실시간 인프라 자체는 범위 밖)",
    where: "자체 AI 앙상블 구성 발상 (lib/selfai.js parts)"},
  {repo: "anthropics/uplifting-biomolecular-modeling", lic: "—", teams: [], status: "해당 없음",
    what: "생체분자 모델링 연구 저장소 — 코인 트레이딩과 무관하여 적용하지 않음",
    where: "—"},
  {repo: "langgenius/dify · dify-plugins", lic: "오픈소스(규칙만)", teams: ["coinai"], status: "부분 적용",
    what: "LLM 앱의 '내 지식으로 답하기(RAG)' + 지식 베이스 + 모델 제공자 추상화 개념 → 앱 지식으로 근거 있는 답을 하는 코인 AI 봇",
    where: "코인 AI 봇 (coinai.js) + 자체 검색(lib/ragstore.js)"},
  {repo: "FlowiseAI/Flowise · FlowiseChatEmbed · FlowiseEmbedReact · FlowiseDocs", lic: "Apache-2.0/MIT(규칙만)", teams: ["coinai"], status: "부분 적용",
    what: "체인·에이전트 흐름을 조합하고 '어디에나 띄우는 채팅 위젯(embed)'으로 내보내는 개념 → 떠다니는 코인 AI 채팅 위젯과 신호 조합",
    where: "코인 AI 봇 떠다니는 위젯 (coinai.js mountLauncher·채팅 UI)"},
  {repo: "Mintplex-Labs/anything-llm · anythingllm-embed · -extension · -mobile · -docs", lic: "MIT", teams: ["coinai"], status: "적용(원본 import·이식)",
    what: "원본 useSessionId.js·constants.js·date.js 를 vendor/anythingllm-embed/ 에 그대로 보관. constants.js(CHAT_UI_REOPEN)는 코인 AI 봇에서 그대로 import 해 '위젯 열림 상태 기억'에 사용. useSessionId/useChatHistory 세션·대화기록 방식은 React 제거해 이식. 외부 키 없으면 추출 답변하는 완전 자체 RAG 구조",
    where: "vendor/anythingllm-embed/*(원본, constants.js는 실제 import) · 코인 AI 봇 세션/대화기록/리셋(coinai.js)"},
  {repo: "probot/probot · template · create-probot-app · probot.github.io", lic: "ISC", teams: [], status: "해당 없음",
    what: "GitHub App(깃허브 웹훅 봇) 프레임워크 — 코인 트레이딩 데스크톱 앱과 무관하여 적용하지 않음",
    where: "—"},
  {repo: "Autumn-27/ARTEX", lic: "AGPL-3.0 (코드 복사 없음·설계 아이디어만)", teams: ["hq", "selfai", "bot"], status: "부분 적용(공격 기능 전부 제외)",
    what: "ARTEX 는 보안 공격(레드팀)용 자율 도구라, 그 공격류 기능은 하나도 넣지 않았다. 범용 멀티에이전트 설계만 재구현: planner 가 공유 todolist 로 다음 의도만 던지고 · worker 가 의도 하나씩 실행 · 결과를 공유 보드에 혈연 링크(어느 의도가 무엇을 냈나)로 축적 · 선행조건과 중복을 관리. 쓰는 것은 기존 코인 데이터·백테스트·자체 AI 판단뿐",
    where: "lib/planner.js(todolist·선행조건·디듀프) · lib/board.js(공유 보드·lineage) · coin-office plannerJob('plan' job, 자동 업무 회전·음성·봇 조종판 [🧭 리서치 플래너]) · 코인 AI 봇 지식(보드)"},
  {repo: "NousResearch/hermes-agent", lic: "MIT", teams: ["hq", "selfai", "bot", "coinai"], status: "부분 — 교훈을 AI 프롬프트에 주입(코드 결정엔 미사용)",
    what: "경험에서 교훈(스킬)을 만들고, 쓰면서 강화하고, 상황에 맞게 떠올리는 자기개선 학습 루프 → 모든 에이전트가 공유하는 '배운 것' 메모리. 공격 요소 없는 범용 에이전트 프레임워크",
    where: "lib/lessons.js(학습·강화·회상) · personaOf 로 전 에이전트 프롬프트에 주입 · plannerJob·selfaiJob·botImproveJob 가 교훈을 기록 · 코인 AI 봇 지식"},
  {repo: "AIPentest/CyberStrikeAI · 0x4m4/hexstrike-ai · usestrix/strix · oritera/Cairn", lic: "각 OSS", teams: [], status: "해당 없음(제외)",
    what: "모두 보안 공격(레드팀)용 자율 AI 도구라 거래 앱에 넣지 않는다. clone 해 내용만 확인했고, vendor 보관·포팅은 하지 않았다",
    where: "—"},
  {repo: "jjs523/day_trading_bot", lic: "OSS", teams: ["news", "selfai", "coinai"], status: "실동작 — 시장 심리 극단(≥85·≤15) 쏠림 방향 진입 크기 절반",
    what: "뉴스 감정 → 종합 심리점수(0~100)+판정으로 매매에 반영하는 방식(sentiment.py analyze_news)을 브라우저용 '사전 기반 자체 감정 엔진'으로 이식 — 외부 FinBERT/pickle 없이 오프라인. 가격+감정 결합 아이디어는 자체 AI 앙상블에 '뉴스 감정' 한 표로",
    where: "lib/sentiment.js · sentimentJob(뉴스팀 '시장 심리') · lib/selfai.js sent 신호 · 코인 AI 봇 지식 · window.ghCoinSentiment"},
  {repo: "jaehong-k/Moral_Emotion_Dataset (KOME)", lic: "연구 공개", teams: ["news"], status: "실동작 — 심리 엔진 어휘(위 관문에 사용)",
    what: "KOME 49,663건 감정 라벨 데이터를 실제로 처리해 긍정 감정 어휘를 데이터로 추출 → 감정 사전에 반영(모델 ckpt 는 쓰지 않고 어휘만). 추출본은 gh-coin/lib/sentiment_lexicon.json",
    where: "자체 감정 엔진 사전(lib/sentiment.js LEX)"},
  {repo: "rickiepark/ml-ko", lic: "MIT", teams: ["ml", "selfai"], status: "실동작 — 기준선보다 나은 ML 모델의 반대 확률 60%↑ 진입 0.7배",
    what: "박해선 머신러닝 교재 코드 — 표준화·여러 모델 결합(소프트보팅) 등 ML 방법론 참고. 자체 AI 앙상블이 가격 ML + 감정 등 여러 신호를 가중 결합하는 설계에 반영",
    where: "lib/selfai.js(신호 가중 결합) · 머신러닝·딥러닝팀"},
  {repo: "gitlabhq/gitlabhq", lic: "MIT", teams: [], status: "해당 없음",
    what: "GitLab(깃 호스팅 플랫폼, Ruby on Rails) — 코인 트레이딩 앱과 무관하여 적용하지 않음",
    where: "—"},
  {repo: "virattt/ai-hedge-fund", lic: "OSS", teams: ["ic"], status: "실동작 — 페르소나 합의도(icConsensus)가 위원회 관문 조건",
    what: "투자 대가(버핏·멍거 등) 페르소나를 AI 에이전트로 → 투자위원회 강세·약세 리서처가 매 안건마다 다른 투자 철학(가치·역발상·모멘텀·매크로·퀀트·리스크패리티)으로 토론",
    where: "투자위원회(ic) IC_PERSONAS"},
  {repo: "FinStep-AI/ContestTrade", lic: "OSS", teams: ["demo"], status: "실동작 — 앙상블 비중이 데모 진입 크기에 곱해짐(콘테스트 표는 표시)",
    what: "내부 경쟁으로 상위 성과만 채택하는 메커니즘 → 데모 전략을 수익·승률·손익비로 겨뤄 순위, 상위에 비중·실거래 우선권, 하위는 은퇴 검토",
    where: "데모거래팀 '전략 콘테스트'(contestJob)"},
  {repo: "io-uty/crypto-auto-trading · bigpie1367/trading-bot · multicore-it/robobytes · beenchangseo/binance-trading-bot", lic: "각 OSS", teams: ["bot"], status: "실동작 — 뉴럴 매매법: 6전략 가중 앙상블(가중치 자동 최적화)·스토RSI·SAR·다우·ATR 그리드 (워크포워드 통과한 것만 실전)",
    what: "RSI·MACD·볼린저·EMA·그리드 기반 코인 자동매매 봇들. 그 전략 방식은 GH Coin 봇 템플릿(추세·돌파·평균회귀·MACD·켈트너 등)과 그리드/DCA(lib/botsim.js)에 이미 들어 있어 새로 추가할 것은 없음(확인 후 크레딧)",
    where: "자동매매봇팀 봇 전략 · lib/botsim.js"},
  {repo: "tuchongkim/visualize-binance (SolTrade)", lic: "OSS", teams: ["qrisk", "selfai"], status: "실동작 — 재고 위험: 같은 방향 쏠림 시 진입 크기 절반(데모·뉴럴)",
    what: "마켓 메이킹(호가 양방향 제시) 모델 — GH Coin 은 단일 포지션·추세 매매 중심이라 복잡·고위험의 MM 은 넣지 않음. 아이디어만 기록",
    where: "—"},
  {repo: "cubexch/ai-fund · 0xSanei/darwinia · chrisworsey55/atlas-gic · chunxiaoxx/Nautilus", lic: "각 OSS", teams: ["demo", "dev"], status: "적용",
    what: "경제적 생존 압박: KPI 미달 해고(ai-fund) · 다윈주의 약자도태·강자번식(darwinia) · 샤프 기반 자기개선 루프(atlas-gic) · 진화 못하면 제거(Nautilus). 전부 가상(데모)자금에서만 구현 — 실자금·실지갑 없음",
    where: "'생존 경쟁'(survivalJob): 개발자 KPI·성과경고/재교육 + 다윈 전략 진화(lib/evolve.js 변이 → 검증 통과+부모보다 나은 후손만 번식) · 적응형 재학습(약자 도태)"},
  {repo: "CyberImmortal/clawdrive · Conway Automaton", lic: "각 OSS", teams: [], status: "미적용(안전상)",
    what: "'돈 못 벌면 죽는다' — 실제 지갑·실자금으로 자율 트레이딩·자가진화. 실자금 자율운용은 사기·해킹·손실 위험이 커서 넣지 않음. 생존 압박은 가상자금 버전으로만 구현",
    where: "— (생존 개념은 위 survivalJob 가 가상자금으로 대체)"},
  {repo: "virattt/ai-hedge-fund · LynchzDEV/ai-auto-trader-ahh", lic: "각 OSS", teams: ["ic"], status: "실동작 — 페르소나 합의도(icConsensus)가 위원회 관문 조건",
    what: "투자 대가 12 페르소나(버핏·멍거·소로스·달리오·우드·린치·차노스·버리·사이먼스 등) · 멀티에이전트 토론 합의(debate consensus)",
    where: "투자위원회(icJob) IC_PERSONAS 12명 · icConsensus(투표 집계로 합의 방향·강도)"},
  {repo: "Ganador1/FenixAI · quentinjeon/openclaw-trade", lic: "각 OSS", teams: ["ic", "news", "qrisk"], status: "실동작 — 뉴스 위험(주요 일정 임박) → 신규 진입 45분 중지(뉴럴+사무실)",
    what: "멀티에이전트 파이프라인(분석→전략→리스크→실행→포트폴리오) · 메모리로 역량 진화(ReasoningBank) · 뉴스로 고위험 시 익스포저 축소",
    where: "파이프라인(분석팀→매매법→백테스트→데모→실거래) · 교훈 메모리(lib/lessons.js) · 시장심리/뉴스(sentimentJob·economyCheck) · 퀀트 리스크(qriskJob)"},
  {repo: "The-Quant-Trading-Vault · pupedator · enarjord/passivbot · bengalm/ninjabot · SteWolk/kuegiBot · Darthreign/KuCoin-EMA-Scanner · pkdoddamani/binance-futures-bot", lic: "각 OSS", teams: ["demo", "bot"], status: "적용",
    what: "다양한 코인선물 전략: 돌파(돈치안)·슈퍼트렌드 추세캐리·변동성 타겟(ADX+ATR 사이징)·그리드형 반복·평균회귀(통계)·RSI/MACD/EMA",
    where: "준비된 매매법 프리셋 12종(lib/presets.js) · 프리셋 비교(presetJob) · 자동매매봇 템플릿 · 그리드/DCA(lib/botsim.js)"},
  {repo: "beebots · SnowingFox/open-nof1.ai · dsh-crypto-workbench · HuseynBabakhanov · TerminalGravity/blofin-app", lic: "각 OSS", teams: ["demo", "selfai", "combo", "ml"], status: "표시용 — 콘테스트·타점판 개념",
    what: "봇/모델 경쟁 아레나 · 기회 레이더/스캔(여러 코인 선물 기회 탐지)",
    where: "전략 콘테스트(신뢰점수 아레나) · 실시간 타점판(6코인×4시간대) · 자체 AI 방향·확신도 순위(selfaiJob) · 알파 팩터 순위(alphaJob)"},
  {repo: "hivemoot · hermes-agent-team · longwindwang1/agent-team · Root-IO-Labs/open-agent-teams · keepongo/routa · msitarzewski/agency-agents", lic: "각 OSS", teams: ["hq"], status: "표시용 — 조직도·회의 구조",
    what: "역할 기반 다중 에이전트 팀·회의·상호 리뷰·칸반 파이프라인(Backlog→Dev→Review→Done)·230+ 전문 페르소나",
    where: "31팀 331명 조직(coin-org.js) · 회의(전략가→반론검토관→리스크→CEO) · #파이프라인 채널 · ARTEX식 플래너/보드(lib/planner.js·board.js)"},
  {repo: "GitHub Models · xtekky/gpt4free · zebbern/no-cost-ai · CodebuffAI/freebuff · awesome-free-models", lic: "각 OSS/무료", teams: [], status: "참고(공급자 추가는 설정에서)",
    what: "무료 LLM 공급자 모음(GitHub Models·DeepSeek·Llama 등). GH Coin 은 NVIDIA·Groq·Cerebras·Gemini·OpenRouter 등 무료 공급자를 이미 지원하며, OpenAI 호환이면 '내 API 직접 연결'로 추가 가능",
    where: "설정 → AI 두뇌(engine.js PROVIDERS·custom) · 무료 키 발급 안내"},
  {repo: "anthropics/financial-services · HKUDS/AI-Trader · benstaf/FinRL_DeepSeek · TauricResearch/TradingAgents · haidrrrry/Ai-trader-pro", lic: "각 OSS", teams: ["selfai", "dev", "demo"], status: "실동작 — 뉴럴 데스크 상시 실행: 검증된 전략 신호 → AI 승인 → 청산공식 사이징",
    what: "연결된 AI 모델이 '직접' 매매·학습·복기·개선하는 트레이딩 데스크: 각 모델이 피처 신호로 데모 포지션 운용 → 손실 복기해 교훈을 스스로 뽑아 다음 판단에 반영(FinRL_DeepSeek식 보상 기반 개선) → 지표 146종을 조합해 매매법+커스텀 수식 지표를 설계 → 자동 백테스트 → 통과분을 에이전트 팀(사무실) 데모 장부로 인계(TradingAgents·AI-Trader 핸드오프)",
    where: "🧠 뉴럴 데스크(neural.js·neural-ui.js): modelStep(직접 거래)·reflect(복기 학습)·designStrategy(매매법·커스텀 지표 설계→백테스트→사무실 인계) · 상단 '🧠 뉴럴 데스크' 버튼"},
  {repo: "memvid/claude-brain · toroleapinc/claude-brain · OoneBreath/project-brain · AgriciDaniel/claude-obsidian · ArcInstitute/brain-agent-template", lic: "각 OSS", teams: ["selfai"], status: "실동작 — 뇌 학습(시간대 성적이 리스크 절반, 기억이 AI 승인 자료) · 앱 켜면 상시 실행",
    what: "영속 집단 기억(자체 뇌): 모델들이 복기·거래·설계에서 배운 교훈·승리 패턴·전략을 세션 넘어 누적하고, 다음 판단 때 지금 상황(코인+국면)에 맞는 기억을 꺼내(RAG식 회상) 프롬프트에 주입. 결과로 기억을 강화/쇠퇴(obsidian식 지식 볼트 + brain-agent 기억 그래프 개념)",
    where: "자체 뇌(gh-coin/brain.js): learn/recall/reinforce + 뉴럴 데스크가 modelStep·reflect·designStrategy 에서 뇌를 읽고 씀 · 대시보드 '🧠 자체 뇌 · 누적 기억' 패널"},
  {repo: "obsidianmd/jsoncanvas · obsidian-api · obsidian-clipper · obsidian-help · obsidian-sample-plugin · obsidian-releases", lic: "MIT 등 각 OSS", teams: ["selfai"], status: "표시용 — 뇌 지식 그래프·.canvas 내보내기",
    what: "자체 뇌의 지식 그래프화(Obsidian 개념): ① 기억끼리 위키링크[[ ]]·백링크로 연결하고 연결 수(degree)로 노드 크기 결정(obsidian-api 그래프 뷰) ② 핵심 규칙이 근거 패턴들에 링크되며 허브로 자람 ③ JSON Canvas(.canvas) 오픈 포맷으로 내보내 실제 Obsidian에서 열기(jsoncanvas) ④ 기억을 원자 노트로 정제(obsidian-clipper distill 개념)",
    where: "brain.js: learn(links)·graph(degree/엣지)·toCanvas(.canvas 내보내기) · neural-ui.js: 🧠 뇌 지식 그래프 카드(Obsidian 그래프 뷰 스타일 — 발광 노드·호버 이웃 강조·degree 크기·.canvas ↓ 버튼)"}
];
export const TECH_REPOS = 64;   // + Obsidian 6종(지식 그래프·위키링크·JSON Canvas)
