// 📚 도입 기술: 대표님이 준 오픈소스 23개를 분석해 어느 부서에 무엇을 넣었는지 (코드 복사 없이 규칙·공식만 다시 만듦)
// status: 적용(실제로 돌아감) · 부분 적용(핵심만) · 참고(아이디어만 — 라이선스·구조상 그대로 쓸 수 없음)
export const TECH = [
  {repo: "freqtrade/freqtrade", lic: "GPL-3.0", teams: ["opt", "tpsl", "bt", "demo"], status: "적용",
    what: "시간별 목표 수익표(minimal_roi) · 수익 오프셋 뒤 추적손절 · 보호장치 4종(StoplossGuard·MaxDrawdown·CooldownPeriod·LowProfitPairs) · 하이퍼옵트 손실함수 10종(Sharpe·Sortino·Calmar·ProfitDrawDown·MultiMetric·ShortTradeDur 등)과 ROI/손절/추적손절 탐색 공간 · 기대값 비율",
    where: "백테스터(nuri-ai/quant.js risk.minimal_roi·protections) · 전략 최적화팀 '하이퍼옵트' 업무 · 백테스트팀 '검증 보강' 표"},
  {repo: "mementum/backtrader", lic: "GPL-3.0", teams: ["bt", "opt", "demo"], status: "적용",
    what: "성과 분석기: SQN(등급) · VWR(변동성 가중 수익, 코드 기본값 tau 0.2·sdev_max 2.0) · Returns 연환산 · DrawDown 최장 물림 · TradeAnalyzer 연승·연패",
    where: "백테스트팀 '검증 보강' 표 · 전략 최적화팀 결과표 (lib/hyperopt.js analyzers)"},
  {repo: "nautechsystems/nautilus_trader", lic: "LGPL-3.0", teams: ["qrisk", "live", "entry"], status: "적용",
    what: "주문 전 리스크 엔진 점검 순서(축소 전용·가격/수량 단위·최소/최대·주문당 금액·거래 상태·제출 속도) · 거래 상태 ACTIVE/REDUCING/HALTED · TWAP 분할 · 고정 위험 사이저",
    where: "퀀트 리스크팀 '주문 전 점검표' · 실거래 데스크(거래 상태·TWAP 계획) · 진입 타점팀 '1% 위험 크기' (lib/execution.js) — 실제 주문은 여전히 보호 파일 live.js 한도·승인"},
  {repo: "vnpy/vnpy", lic: "MIT", teams: ["qrisk", "live", "ml"], status: "적용",
    what: "리스크 매니저(주문 흐름·하루 거래 한도) · 아이스버그 분할 · Alpha158 계열 팩터(KMID·KLEN·ROC·MA·STD·BETA·RSV·CORR) + 견고 z점수 횡단면 순위",
    where: "주문 전 점검표 · 머신러닝·딥러닝팀 '알파 팩터 순위' (lib/alpha.js) · N분봉 합성은 기존 차트 터미널(3·6·8·10분봉)에 이미 있음"},
  {repo: "ccxt/ccxt", lic: "MIT", teams: ["data", "situ"], status: "적용",
    what: "통일 API 개념으로 8개 거래소 공개 시세·펀딩·미결제약정 맞추기(바이낸스·바이비트 v5·OKX v5·비트겟 v2·코인베이스·크라켄·업비트·빗썸) · 단위 함정(OKX 계약·소수 변동률·펀딩 주기) · 김치 프리미엄 · 거래소별 요청 간격",
    where: "데이터 플랫폼팀 '거래소 비교' (lib/exchanges.js) — 라이브러리 자체(수 MB)는 넣지 않고 공개 주소만 사용"},
  {repo: "openbq-org/OpenBB (OpenBB ODP 미러)", lic: "Apache-2.0", teams: ["news", "data"], status: "부분 적용",
    what: "공급원(provider) 구조 · 키 없이 쓰는 공개 주소: Nasdaq 경제 캘린더 · 뉴욕 연준 SOFR · FRED CSV · Deribit DVOL",
    where: "뉴스·경제지표팀 '경제 캘린더·금리·변동성 지수' 업무 — 일부 사이트는 브라우저 차단(CORS)이 있어 GHCoin.exe 실행기로 받음"},
  {repo: "goldmansachs/gs-quant", lic: "Apache-2.0", teams: ["qrisk"], status: "적용",
    what: "시계열: 수익률 · 연율 변동성(표본 표준편차 × √연간 관측, 코인은 365) · EWMA 변동성 · 상관 · 베타 · z점수 · 백분위 · 최대 낙폭 · 튀는 값 다듬기 · 시나리오 충격(비트코인 −30%, 알트는 베타만큼) + 역사적·모수 VaR/CVaR",
    where: "퀀트 리스크팀 '코인별 위험'·'스트레스 시험' (lib/riskq.js)"},
  {repo: "goldmansachs/jdmn", lic: "Apache-2.0", teams: ["qrisk", "demo", "live"], status: "적용",
    what: "DMN 결정표: 단항 검사(-, <, [a..b], (a..b], not(), 목록) · 적중 정책 UNIQUE·FIRST·PRIORITY·ANY·COLLECT(+,<,>,#)·RULE/OUTPUT ORDER · 기본 출력 · 맞은 규칙 번호 기록",
    where: "퀀트 리스크팀 '리스크 판정' 결정표 · 데모→실거래 '승격 결정표'(거부>검토>데모 더>승인) (lib/dmn.js)"},
  {repo: "goldmansachs/legend-engine · legend-studio · legend-sdlc · finos/legend", lic: "Apache-2.0", teams: ["data", "dev", "hq"], status: "적용",
    what: "데이터 모델 제약(Error는 막고 Warn은 경고, 결함 모두 모음) · 작업공간→검토→승인→버전 흐름 · 버전 번호(논리 변경 MAJOR · 파라미터 MINOR · 위험 설정 PATCH) · 경로별 차이(diff)",
    where: "매매법 개발 전 '전략 제약 검사' · 백테스트 통과 시 버전 발행 · 하이퍼옵트 결과 검토·승인 · 캔들 품질 검사 (lib/sdlc.js)"},
  {repo: "goldmansachs/obevo", lic: "Apache-2.0", teams: ["data", "hq"], status: "적용",
    what: "변경 이름 + 체크섬 적용 기록 · 이미 한 변경은 건너뜀 · 내용이 바뀐 변경은 멈추고 알림 · 실패 시 백업으로 되돌림 · 다시 돌려도 되는 변경",
    where: "앱 시작 때 저장소 이전(lib/migrate.js) · 데이터 플랫폼팀 상태표"},
  {repo: "goldmansachs/reladomo", lic: "Apache-2.0", teams: ["data", "ic", "qrisk"], status: "적용",
    what: "이중 시간(업무 시간 from~thru · 처리 시간 in~out) · 감사 전용 기록 · 정정은 새 행(옛 기록 보존) · as-of 조회 · 해시 사슬 검증",
    where: "투자위원회 결정·채점, 리스크 판정, 백테스트, 하이퍼옵트 버전 기록 (lib/journal.js)"},
  {repo: "TauricResearch/TradingAgents", lic: "Apache-2.0", teams: ["ic"], status: "적용",
    what: "애널리스트 4명(시장·여론·뉴스·펀더멘털) → 강세·약세 토론(1라운드) → 리서치 매니저 5단계 등급 → 트레이더(절대 가격만) → 공격·보수·중립 리스크 토론 → 위원장 최종 등급 · '의견 충돌은 관망 사유가 아님' · 해석 불가는 REVIEW(거래 금지) · 5봉 뒤 비트코인 대비 알파 채점 → 2~4문장 교훈 → 최종 결정자에게만(같은 코인 5 + 다른 코인 3, 시점 이전 것만)",
    where: "새 부서 '투자위원회' (coin-office icJob) · 뉴스팀 여론 밴드"},
  {repo: "HKUDS/Vibe-Trading", lic: "MIT", teams: ["dev", "bt", "opt", "news"], status: "적용",
    what: "말 → 전략 → 백테스트 흐름의 위생 관문(거래 0건·NaN 금지, 늦은 첫 거래·낮은 노출·끝까지 열린 포지션 경고) · 순열 검정 p · 부트스트랩 샤프 구간 · 5구간 검증 · 펀딩 상태(과열·쏠림) 규칙",
    where: "백테스트팀 '검증 보강' · 전략 최적화팀 채택 조건 · 승격 결정표 (lib/robust.js, exchanges.fundingRegime)"},
  {repo: "BennyThadikaran/stock-pattern", lic: "GPL-3.0", teams: ["pattern"], status: "적용",
    what: "피벗(좌우 6봉, 마감 봉만 → 미래 참조 없음) · 허용오차 = 봉 길이 중앙값 · 쌍봉·쌍바닥 · 헤드앤숄더(역) · VCP · 깃발 · 추세선(3번 닿음)",
    where: "차트·캔들 패턴팀 '패턴 스캐너' (lib/patterns.js) + 형성→돌파→목표/실패 상태"},
  {repo: "zeta-zetra/chart_patterns", lic: "라이선스 없음(아이디어만)", teams: ["pattern"], status: "참고",
    what: "피벗 회귀선 분류(삼각수렴·깃발·페넌트·쌍봉) — 기울기를 ATR/봉으로 정규화하고 쐐기·채널을 더함, 원본 버그(한쪽 점만 확인) 수정",
    where: "패턴 스캐너의 기하 패턴 부분 (코드 없이 규칙만)"},
  {repo: "BitOracle-bitoracle/bitoracle-ai-server", lic: "라이선스 없음(아이디어만)", teams: ["ml"], status: "참고",
    what: "다음 1시간 상승 확률 밴드: p ≥ 0.60 진입 · 0.40~0.60 무거래 · 손절 −3% · 익절 +5% (모델은 실시간 데이터로 스케일러를 다시 맞추는 문제가 있어 가져오지 않음)",
    where: "머신러닝·딥러닝팀 ML 확률 전략 규칙"},
  {repo: "iliaal/tradingview-mcp", lic: "MIT", teams: ["combo"], status: "부분 적용",
    what: "트레이딩뷰 데스크톱 조작용(주문 없음) — 우리 앱엔 데스크톱 연결이 없어 '기술적 분석 요약'(이평 15표 + 오실레이터 11표, 강한 매수~강한 매도)을 MIT python-tradingview-ta 규칙으로 직접 계산",
    where: "실시간 종합 지표 타점판 'TV 요약' 열 · 투자위원회 시장 보고 (lib/ta_rating.js) + 캔들 패턴 17종"},
  {repo: "johnmackintosh/runcharter", lic: "GPL-3.0", teams: ["demo"], status: "적용",
    what: "런 차트: 처음 13점 중앙값 → 9연속 위/아래면 지속 이동 → 그 9점으로 새 중앙값 (중앙값과 같은 점은 건너뜀)",
    where: "데모거래팀 '성과 이동 감지' · 승격 결정표의 '악화' 입력 (lib/runchart.js)"},
  {repo: "jh941213/my-cc-harness", lic: "MIT", teams: ["hq"], status: "적용",
    what: "독립 QA(만든 사람과 다른 직원) 100점 채점: 기능 40 · 품질 25 · 군더더기 없음 20 · 사용성·보안 15, 85↑ 통과 · 65~84 조건부 · 치명적 하나면 불합격 · 증거 없는 완료 금지",
    where: "CEO실 코드 수정안 → QA 채점 후 대표 승인"},
  {repo: "enarjord/passivbot", lic: "Unlicense(공개)", teams: ["bot"], status: "부분 적용",
    what: "그리드·DCA(물타기) 봇 방식: 간격·물타기 배수(ddown)·최대 물타기·지갑 노출 한도·익절 마크업. 핵심은 '무한 물타기 금지'를 위한 지갑 노출 한도·물타기 횟수 상한",
    where: "자동매매봇팀 '그리드/DCA 연구 백테스트' (lib/botsim.js) — 청산 위험 때문에 연구용 백테스트로만, 실거래로는 안 나감"},
  {repo: "jesse-ai/jesse", lic: "MIT", teams: ["bot"], status: "부분 적용",
    what: "전략 클래스 방식(진입·청산·손절·익절·포지션 사이징)과 백테스트 구조 → 추세추종·평균회귀 봇 전략",
    where: "자동매매봇팀 '추세추종 봇'·'평균회귀 봇' 전략 (coin-office BOT_TEMPLATES)"},
  {repo: "Drakkar-Software/OctoBot", lic: "GPL-3.0(코어)·LGPL(텐타클)", teams: ["bot"], status: "부분 적용",
    what: "트레이딩 모드(그리드·DCA·돌파·신호)와 평가기 개념 → 돌파·슈퍼트렌드 봇 전략",
    where: "자동매매봇팀 '돌파 봇'·'슈퍼트렌드 플립 봇'"},
  {repo: "conor19w/Binance-Futures-Trading-Bot", lic: "라이선스 없음(규칙만)", teams: ["bot"], status: "부분 적용",
    what: "바이낸스 선물 TA 봇의 진입·손절·익절·레버리지 방식 → 추세추종·돌파 봇의 조건·한도",
    where: "자동매매봇팀 봇 전략"},
  {repo: "Erfaniaa/crypto-trading-strategy-backtester", lic: "GPL-3.0(규칙만)", teams: ["bot"], status: "참고",
    what: "단순 교차 전략 백테스트 방식 → 평균회귀·추세 봇 참고",
    where: "자동매매봇팀 봇 전략"},
  {repo: "freqtrade/freqtrade", lic: "GPL-3.0", teams: ["bot"], status: "적용",
    what: "(이미 최적화팀에 반영) ROI 표·추적손절·보호장치를 봇 전략에도 사용",
    where: "자동매매봇팀 '추세 캐리 봇'(minimal_roi) 등"},
  {repo: "RanitManik/gemini-clone", lic: "MIT", teams: ["hq"], status: "적용",
    what: "빈 방 추천 질문 카드 · 최근 질문 목록(방별, 중복 제거 20개) · 한글 입력 중 Enter 오작동 막기",
    where: "본부 채팅창"}
];
export const TECH_REPOS = 29;   // +6 (트레이딩 봇 저장소)   // 대표님이 준 주소 중 중복(freqtrade·nautilus·gs-quant 두 번씩)을 뺀 23개
